# -*- coding: utf-8 -*-
"""Extension catalogue VOLT PC — assortiment "vrai revendeur" sur toutes
les catégories (du petit prix au haut de gamme).

Ajouté via SEED_PRODUCTS.extend(CATALOG_PLUS_PRODUCTS) dans seed.py.
Aucun doublon de nom avec l'existant (vérifié au chargement). Clés de
compat respectées : gpu→tdp_w/length_mm, mobo→socket/ram_type/form_factor,
ram→ram_type, case→max_gpu_mm, psu→watts, cooling→sockets[].
"""

CATALOG_PLUS_PRODUCTS = [
    # ═══ CARTES GRAPHIQUES ═══════════════════════════════════════════
    {"name": "GeForce RTX 5080 Gaming OC", "brand": "Gigabyte", "category": "gpu", "price": 1199.00, "old_price": None, "stock": 6, "rating": 4.8, "featured": True, "badge": "Nouveau", "description": "Blackwell haut de gamme : 4K natif et DLSS 4 pour tout écraser sans broncher.", "specs": {"GPU": "Blackwell GB203", "Mémoire": "16 Go GDDR7", "Boost": "2617 MHz", "TDP": "360 W", "Longueur": "340 mm", "tdp_w": 360, "length_mm": 340}},
    {"name": "GeForce RTX 5090 SUPRIM Liquid", "brand": "MSI", "category": "gpu", "price": 2349.00, "old_price": None, "stock": 2, "rating": 5.0, "featured": True, "badge": "Flagship", "description": "Le sommet absolu Blackwell, watercooling AIO et 32 Go pour la 4K/8K et l'IA.", "specs": {"GPU": "Blackwell GB202", "Mémoire": "32 Go GDDR7", "Boost": "2580 MHz", "TDP": "575 W", "Longueur": "360 mm", "tdp_w": 575, "length_mm": 360}},
    {"name": "GeForce RTX 5060 Ti 8 Go Ventus", "brand": "MSI", "category": "gpu", "price": 399.00, "old_price": None, "stock": 18, "rating": 4.3, "featured": False, "badge": None, "description": "Le 1080p/1440p moderne avec DLSS 4, compacte et silencieuse.", "specs": {"GPU": "Blackwell GB206", "Mémoire": "8 Go GDDR7", "Boost": "2572 MHz", "TDP": "180 W", "Longueur": "230 mm", "tdp_w": 180, "length_mm": 230}},
    {"name": "Radeon RX 9070 GRE 12 Go", "brand": "PowerColor", "category": "gpu", "price": 499.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "RDNA 4 abordable : 12 Go et un 1440p très confortable, ray tracing solide.", "specs": {"GPU": "RDNA 4 Navi 48", "Mémoire": "12 Go GDDR6", "Boost": "2790 MHz", "TDP": "200 W", "Longueur": "280 mm", "tdp_w": 200, "length_mm": 280}},
    {"name": "Arc B570 10 Go", "brand": "Intel", "category": "gpu", "price": 239.00, "old_price": None, "stock": 14, "rating": 4.3, "featured": False, "badge": "Petit prix", "description": "Battlemage d'entrée : du 1080p musclé et un encodeur AV1 au top pour le streaming.", "specs": {"GPU": "Xe2 BMG-G21", "Mémoire": "10 Go GDDR6", "Boost": "2500 MHz", "TDP": "150 W", "Longueur": "245 mm", "tdp_w": 150, "length_mm": 245}},
    {"name": "GeForce RTX 4060 Low Profile", "brand": "Gigabyte", "category": "gpu", "price": 299.00, "old_price": None, "stock": 16, "rating": 4.3, "featured": False, "badge": None, "description": "Format ultra-compact pour les boîtiers SFF et HTPC, sans prise PCIe externe.", "specs": {"GPU": "Ada AD107", "Mémoire": "8 Go GDDR6", "Boost": "2460 MHz", "TDP": "115 W", "Longueur": "182 mm", "tdp_w": 115, "length_mm": 182}},

    # ═══ PROCESSEURS ═════════════════════════════════════════════════
    {"name": "Ryzen 5 8400F", "brand": "AMD", "category": "cpu", "price": 129.00, "old_price": None, "stock": 22, "rating": 4.4, "featured": False, "badge": "Petit prix", "description": "6 cœurs Zen 4 abordables sur AM5 pour un premier PC gamer évolutif.", "specs": {"Cœurs": "6C / 12T", "Fréquence": "4,2 / 4,7 GHz", "Cache": "22 Mo", "Socket": "AM5", "TDP": "65 W", "Graphique": "Non", "socket": "AM5"}},
    {"name": "Core i5-14400F", "brand": "Intel", "category": "cpu", "price": 169.00, "old_price": None, "stock": 20, "rating": 4.5, "featured": False, "badge": None, "description": "10 cœurs hybrides très polyvalents sur LGA1700, idéal config gaming équilibrée.", "specs": {"Cœurs": "10C (6P+4E) / 16T", "Fréquence": "2,5 / 4,7 GHz", "Cache": "20 Mo", "Socket": "LGA1700", "TDP": "65 W", "Graphique": "Non", "socket": "LGA1700"}},
    {"name": "Athlon 3000G", "brand": "AMD", "category": "cpu", "price": 55.00, "old_price": None, "stock": 28, "rating": 4.2, "featured": False, "badge": "Petit prix", "description": "Dual-core avec Radeon Vega intégré, parfait pour un PC bureautique AM4 à bas coût.", "specs": {"Cœurs": "2C / 4T", "Fréquence": "3,5 GHz", "Cache": "5 Mo", "Socket": "AM4", "TDP": "35 W", "Graphique": "Vega 3", "socket": "AM4"}},

    # ═══ MÉMOIRE RAM ═════════════════════════════════════════════════
    {"name": "Vengeance RGB 32 Go DDR5-6000 CL30", "brand": "Corsair", "category": "ram", "price": 124.00, "old_price": None, "stock": 24, "rating": 4.8, "featured": True, "badge": None, "description": "Le kit DDR5 RGB de référence pour AM5 : 6000 CL30 EXPO, stable et lumineux.", "specs": {"Capacité": "32 Go (2x16)", "Type": "DDR5", "Fréquence": "6000 MT/s", "Latence": "CL30", "Profils": "EXPO + XMP 3.0", "ram_type": "DDR5"}},
    {"name": "Ripjaws S5 32 Go DDR5-5600", "brand": "G.Skill", "category": "ram", "price": 99.00, "old_price": None, "stock": 26, "rating": 4.6, "featured": False, "badge": None, "description": "32 Go DDR5 sobres et fiables, profil bas sans RGB pour configs discrètes.", "specs": {"Capacité": "32 Go (2x16)", "Type": "DDR5", "Fréquence": "5600 MT/s", "Latence": "CL36", "Profils": "EXPO + XMP 3.0", "ram_type": "DDR5"}},
    {"name": "Vengeance 64 Go DDR5-6000", "brand": "Corsair", "category": "ram", "price": 209.00, "old_price": None, "stock": 14, "rating": 4.7, "featured": False, "badge": None, "description": "64 Go DDR5 pour la création vidéo, la 3D et la virtualisation sur plateforme moderne.", "specs": {"Capacité": "64 Go (2x32)", "Type": "DDR5", "Fréquence": "6000 MT/s", "Latence": "CL30", "Profils": "EXPO + XMP 3.0", "ram_type": "DDR5"}},
    {"name": "Fury Beast RGB 32 Go DDR5-6000", "brand": "Kingston", "category": "ram", "price": 114.00, "old_price": None, "stock": 20, "rating": 4.7, "featured": False, "badge": None, "description": "32 Go DDR5 RGB performants et accessibles, compatibles Intel et AMD.", "specs": {"Capacité": "32 Go (2x16)", "Type": "DDR5", "Fréquence": "6000 MT/s", "Latence": "CL36", "Profils": "EXPO + XMP 3.0", "ram_type": "DDR5"}},
    {"name": "SO-DIMM Impact 16 Go DDR5-5600", "brand": "Kingston", "category": "ram", "price": 59.00, "old_price": None, "stock": 18, "rating": 4.6, "featured": False, "badge": None, "description": "Barrettes SO-DIMM pour portables et mini-PC, mise à niveau facile et rapide.", "specs": {"Capacité": "16 Go (2x8)", "Type": "DDR5 SO-DIMM", "Fréquence": "5600 MT/s", "Latence": "CL40", "Profils": "—", "ram_type": "DDR5"}},

    # ═══ STOCKAGE ════════════════════════════════════════════════════
    {"name": "990 EVO Plus 1 To", "brand": "Samsung", "category": "storage", "price": 89.00, "old_price": None, "stock": 30, "rating": 4.7, "featured": False, "badge": None, "description": "NVMe polyvalent (Gen4 x4 / Gen5 x2), rapide et endurant pour disque système.", "specs": {"Capacité": "1 To", "Interface": "PCIe 4.0 x4", "Lecture": "7150 Mo/s", "Écriture": "6300 Mo/s", "Endurance": "600 TBW", "Format": "M.2 2280"}},
    {"name": "Crucial T705 2 To Gen5", "brand": "Crucial", "category": "storage", "price": 269.00, "old_price": None, "stock": 10, "rating": 4.8, "featured": True, "badge": "Nouveau", "description": "Le NVMe Gen5 le plus rapide : débits records pour les créateurs et la 4K gaming.", "specs": {"Capacité": "2 To", "Interface": "PCIe 5.0 x4", "Lecture": "14500 Mo/s", "Écriture": "12700 Mo/s", "Endurance": "1200 TBW", "Format": "M.2 2280"}},
    {"name": "WD_Black SN850X 2 To", "brand": "Western Digital", "category": "storage", "price": 169.00, "old_price": None, "stock": 16, "rating": 4.8, "featured": False, "badge": None, "description": "2 To Gen4 gaming au top : débits élevés, dissipateur en option et grosse endurance.", "specs": {"Capacité": "2 To", "Interface": "PCIe 4.0 x4", "Lecture": "7300 Mo/s", "Écriture": "6600 Mo/s", "Endurance": "1200 TBW", "Format": "M.2 2280"}},
    {"name": "WD Red Pro 8 To NAS", "brand": "Western Digital", "category": "storage", "price": 229.00, "old_price": None, "stock": 12, "rating": 4.7, "featured": False, "badge": None, "description": "Disque NAS 7200 tr/min pensé pour le RAID 24/7, fiable et endurant.", "specs": {"Capacité": "8 To", "Interface": "SATA III", "Vitesse": "7200 tr/min", "Cache": "256 Mo", "Usage": "NAS / RAID", "Format": "3.5\""}},
    {"name": "Portable SSD T7 1 To", "brand": "Samsung", "category": "storage", "price": 99.00, "old_price": None, "stock": 20, "rating": 4.7, "featured": False, "badge": None, "description": "SSD externe USB 3.2 ultra-compact, parfait pour transporter projets et sauvegardes.", "specs": {"Capacité": "1 To", "Interface": "USB 3.2 Gen2", "Lecture": "1050 Mo/s", "Écriture": "1000 Mo/s", "Format": "Externe"}},

    # ═══ CARTES MÈRES ════════════════════════════════════════════════
    {"name": "B650 Tomahawk WiFi", "brand": "MSI", "category": "motherboard", "price": 199.00, "old_price": None, "stock": 14, "rating": 4.7, "featured": True, "badge": None, "description": "La référence AM5 milieu de gamme : VRM costaud, WiFi 6E et double M.2 Gen4.", "specs": {"Socket": "AM5", "Chipset": "B650", "Format": "ATX", "Mémoire": "4x DDR5 6400+", "M.2": "2 slots Gen4", "Réseau": "2.5 GbE + WiFi 6E", "socket": "AM5", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "X670E Carbon WiFi", "brand": "MSI", "category": "motherboard", "price": 379.00, "old_price": None, "stock": 8, "rating": 4.7, "featured": False, "badge": None, "description": "Plateforme AM5 haut de gamme : PCIe 5.0 partout, connectique massive et WiFi 6E.", "specs": {"Socket": "AM5", "Chipset": "X670E", "Format": "ATX", "Mémoire": "4x DDR5 6600+", "M.2": "4 slots (Gen5)", "Réseau": "2.5 GbE + WiFi 6E", "socket": "AM5", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "B650M-A WiFi", "brand": "ASUS", "category": "motherboard", "price": 159.00, "old_price": None, "stock": 16, "rating": 4.5, "featured": False, "badge": None, "description": "Micro-ATX AM5 complète et fiable, idéale pour un montage compact et performant.", "specs": {"Socket": "AM5", "Chipset": "B650", "Format": "Micro-ATX", "Mémoire": "4x DDR5 6400", "M.2": "2 slots Gen4", "Réseau": "2.5 GbE + WiFi 6", "socket": "AM5", "ram_type": "DDR5", "form_factor": "mATX"}},
    {"name": "Z790 AORUS Elite AX", "brand": "Gigabyte", "category": "motherboard", "price": 269.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "LGA1700 haut de gamme pour overclocking DDR5 et CPU K, WiFi 6E et 4x M.2.", "specs": {"Socket": "LGA1700", "Chipset": "Z790", "Format": "ATX", "Mémoire": "4x DDR5 7600+", "M.2": "4 slots Gen4", "Réseau": "2.5 GbE + WiFi 6E", "socket": "LGA1700", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "Z890 Pro RS WiFi", "brand": "ASRock", "category": "motherboard", "price": 289.00, "old_price": None, "stock": 9, "rating": 4.5, "featured": False, "badge": "Nouveau", "description": "Plateforme LGA1851 pour Core Ultra : PCIe 5.0, Thunderbolt 4 et WiFi 7.", "specs": {"Socket": "LGA1851", "Chipset": "Z890", "Format": "ATX", "Mémoire": "4x DDR5 8200+", "M.2": "4 slots (Gen5)", "Réseau": "2.5 GbE + WiFi 7", "socket": "LGA1851", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "B650E-I ROG Strix", "brand": "ASUS", "category": "motherboard", "price": 299.00, "old_price": None, "stock": 7, "rating": 4.6, "featured": False, "badge": None, "description": "Mini-ITX AM5 premium pour un PC SFF surpuissant : PCIe 5.0 et WiFi 6E.", "specs": {"Socket": "AM5", "Chipset": "B650E", "Format": "Mini-ITX", "Mémoire": "2x DDR5 6400+", "M.2": "2 slots (Gen5)", "Réseau": "2.5 GbE + WiFi 6E", "socket": "AM5", "ram_type": "DDR5", "form_factor": "ITX"}},

    # ═══ ALIMENTATIONS ═══════════════════════════════════════════════
    {"name": "RM750e ATX 3.1", "brand": "Corsair", "category": "psu", "price": 109.00, "old_price": None, "stock": 20, "rating": 4.8, "featured": True, "badge": None, "description": "750 W 80+ Gold full modulaire, câble 12V-2x6 natif pour GPU récents.", "specs": {"Puissance": "750 W", "Certification": "80+ Gold", "Norme": "ATX 3.1", "Modulaire": "Full", "Garantie": "7 ans", "watts": 750}},
    {"name": "RM1000e ATX 3.1", "brand": "Corsair", "category": "psu", "price": 169.00, "old_price": None, "stock": 12, "rating": 4.8, "featured": False, "badge": None, "description": "1000 W 80+ Gold full modulaire pour configs RTX 5080/5090 sans compromis.", "specs": {"Puissance": "1000 W", "Certification": "80+ Gold", "Norme": "ATX 3.1", "Modulaire": "Full", "Garantie": "10 ans", "watts": 1000}},
    {"name": "Pure Power 12 M 650 W", "brand": "be quiet!", "category": "psu", "price": 89.00, "old_price": None, "stock": 18, "rating": 4.6, "featured": False, "badge": None, "description": "650 W 80+ Gold silencieuse et modulaire, parfaite pour une config milieu de gamme.", "specs": {"Puissance": "650 W", "Certification": "80+ Gold", "Norme": "ATX 3.0", "Modulaire": "Full", "Garantie": "10 ans", "watts": 650}},
    {"name": "Focus GX-1000 ATX 3.1", "brand": "Seasonic", "category": "psu", "price": 179.00, "old_price": None, "stock": 10, "rating": 4.9, "featured": False, "badge": None, "description": "1000 W 80+ Gold haut de gamme, fiabilité Seasonic et garantie 12 ans.", "specs": {"Puissance": "1000 W", "Certification": "80+ Gold", "Norme": "ATX 3.1", "Modulaire": "Full", "Garantie": "12 ans", "watts": 1000}},
    {"name": "Prime TX-1300 Titanium", "brand": "Seasonic", "category": "psu", "price": 359.00, "old_price": None, "stock": 5, "rating": 4.9, "featured": False, "badge": None, "description": "1300 W 80+ Titanium, le rendement ultime pour stations de travail et configs extrêmes.", "specs": {"Puissance": "1300 W", "Certification": "80+ Titanium", "Norme": "ATX 3.1", "Modulaire": "Full", "Garantie": "12 ans", "watts": 1300}},
    {"name": "MWE White 500 W", "brand": "Cooler Master", "category": "psu", "price": 45.00, "old_price": None, "stock": 26, "rating": 4.2, "featured": False, "badge": "Petit prix", "description": "500 W 80+ pour une config bureautique ou un GPU d'entrée, simple et fiable.", "specs": {"Puissance": "500 W", "Certification": "80+ White", "Norme": "ATX 2.52", "Modulaire": "Non", "Garantie": "3 ans", "watts": 500}},

    # ═══ BOÎTIERS ════════════════════════════════════════════════════
    {"name": "North", "brand": "Fractal Design", "category": "case", "price": 139.00, "old_price": None, "stock": 14, "rating": 4.8, "featured": True, "badge": None, "description": "Boîtier ATX au design bois/verre élégant, excellent flux d'air et finitions soignées.", "specs": {"Format": "ATX", "GPU max": "355 mm", "Ventilateurs": "Jusqu'à 7", "Façade": "Mesh + bois", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 355}},
    {"name": "H6 Flow RGB", "brand": "NZXT", "category": "case", "price": 119.00, "old_price": None, "stock": 16, "rating": 4.6, "featured": False, "badge": None, "description": "Mid-tower au look épuré, double chambre et trois ventilateurs RGB inclus.", "specs": {"Format": "ATX", "GPU max": "365 mm", "Ventilateurs": "Jusqu'à 7", "Façade": "Mesh", "Baies": "2x 2.5\" + 1x 3.5\"", "max_gpu_mm": 365}},
    {"name": "Y70 Touch", "brand": "Hyte", "category": "case", "price": 359.00, "old_price": None, "stock": 6, "rating": 4.7, "featured": False, "badge": "Premium", "description": "Boîtier panoramique verre avec écran tactile intégré pour un build vitrine spectaculaire.", "specs": {"Format": "E-ATX", "GPU max": "422 mm", "Ventilateurs": "Jusqu'à 10", "Façade": "Verre incurvé", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 422}},
    {"name": "Core 1000 mATX", "brand": "Fractal Design", "category": "case", "price": 49.00, "old_price": None, "stock": 22, "rating": 4.3, "featured": False, "badge": "Petit prix", "description": "Mini-tour micro-ATX économique et compacte, parfaite pour une première config.", "specs": {"Format": "Micro-ATX", "GPU max": "330 mm", "Ventilateurs": "Jusqu'à 4", "Façade": "Pleine", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 330}},
    {"name": "NR200P V2 ITX", "brand": "Cooler Master", "category": "case", "price": 119.00, "old_price": None, "stock": 12, "rating": 4.7, "featured": False, "badge": None, "description": "La référence SFF Mini-ITX : compacte mais capable d'accueillir un GPU triple slot.", "specs": {"Format": "Mini-ITX", "GPU max": "330 mm", "Ventilateurs": "Jusqu'à 6", "Façade": "Pleine + verre", "Baies": "3x 2.5\" + 1x 3.5\"", "max_gpu_mm": 330}},

    # ═══ REFROIDISSEMENT ═════════════════════════════════════════════
    {"name": "NH-L9i-17xx", "brand": "Noctua", "category": "cooling", "price": 49.00, "old_price": None, "stock": 16, "rating": 4.6, "featured": False, "badge": None, "description": "Ventirad bas profil ultra-compact pour boîtiers SFF et HTPC sur LGA1700.", "specs": {"Type": "Ventirad air bas profil", "Sockets": "LGA1700 / LGA1851", "Ventilateurs": "1x 92 mm PWM", "Hauteur": "37 mm", "TDP supporté": "95 W", "sockets": ["LGA1700", "LGA1851"]}},
    {"name": "Galahad II LCD 360", "brand": "Lian Li", "category": "cooling", "price": 199.00, "old_price": None, "stock": 9, "rating": 4.8, "featured": False, "badge": "Premium", "description": "AIO 360 mm avec écran LCD circulaire, pour dompter les CPU les plus chauds avec style.", "specs": {"Type": "Watercooling AIO 360 mm", "Sockets": "AM5 / AM4 / LGA1700 / LGA1851", "Ventilateurs": "3x 120 mm PWM", "Radiateur": "360 mm", "TDP supporté": "350 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "Assassin X 120 R SE", "brand": "DeepCool", "category": "cooling", "price": 29.00, "old_price": None, "stock": 26, "rating": 4.4, "featured": False, "badge": "Petit prix", "description": "Ventirad simple tour efficace et abordable pour CPU d'entrée et milieu de gamme.", "specs": {"Type": "Ventirad air", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "1x 120 mm PWM", "Hauteur": "154 mm", "TDP supporté": "180 W", "sockets": ["AM5", "AM4", "LGA1700"]}},

    # ═══ ÉCRANS ══════════════════════════════════════════════════════
    {"name": "27GR75Q 27\" QHD 165 Hz IPS", "brand": "LG", "category": "monitor", "price": 219.00, "old_price": None, "stock": 18, "rating": 4.7, "featured": True, "badge": None, "description": "27\" QHD 165 Hz IPS au rapport qualité/prix imbattable pour le gaming polyvalent.", "specs": {"Dalle": "IPS 27\"", "Définition": "2560 × 1440", "Fréquence": "165 Hz", "Réponse": "1 ms", "HDR": "HDR10", "Connectique": "2x HDMI + DP"}},
    {"name": "Odyssey G6 27\" QHD 360 Hz OLED", "brand": "Samsung", "category": "monitor", "price": 649.00, "old_price": None, "stock": 8, "rating": 4.8, "featured": False, "badge": "Premium", "description": "27\" QHD OLED 360 Hz : noirs parfaits et fluidité extrême pour l'e-sport haut de gamme.", "specs": {"Dalle": "QD-OLED 27\"", "Définition": "2560 × 1440", "Fréquence": "360 Hz", "Réponse": "0,03 ms", "HDR": "HDR True Black 400", "Connectique": "HDMI 2.1 + DP"}},
    {"name": "27\" 4K 160 Hz IPS", "brand": "Gigabyte", "category": "monitor", "price": 399.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "27\" 4K 160 Hz IPS, le combo netteté/fluidité idéal pour gaming et création.", "specs": {"Dalle": "IPS 27\"", "Définition": "3840 × 2160", "Fréquence": "160 Hz", "Réponse": "1 ms", "HDR": "HDR400", "Connectique": "HDMI 2.1 + DP"}},
    {"name": "34\" UWQHD 175 Hz Incurvé", "brand": "MSI", "category": "monitor", "price": 379.00, "old_price": None, "stock": 9, "rating": 4.6, "featured": False, "badge": None, "description": "Ultrawide 34\" 21:9 incurvé 175 Hz pour une immersion totale en jeu et productivité.", "specs": {"Dalle": "VA 34\" incurvée 1500R", "Définition": "3440 × 1440", "Fréquence": "175 Hz", "Réponse": "1 ms", "HDR": "HDR400", "Connectique": "2x HDMI + DP"}},
    {"name": "49\" Dual QHD 240 Hz OLED", "brand": "Samsung", "category": "monitor", "price": 999.00, "old_price": 1199.00, "stock": 4, "rating": 4.8, "featured": False, "badge": "Promo", "description": "Super-ultrawide 49\" 32:9 OLED 240 Hz, l'équivalent de deux écrans QHD en un.", "specs": {"Dalle": "QD-OLED 49\" incurvée 1800R", "Définition": "5120 × 1440", "Fréquence": "240 Hz", "Réponse": "0,03 ms", "HDR": "HDR True Black 400", "Connectique": "HDMI 2.1 + DP + USB-C"}},
    {"name": "24G4 24\" FHD 180 Hz", "brand": "AOC", "category": "monitor", "price": 119.00, "old_price": None, "stock": 24, "rating": 4.5, "featured": False, "badge": "Petit prix", "description": "24\" Full HD 180 Hz IPS, l'écran e-sport abordable pour débuter dans la compétition.", "specs": {"Dalle": "IPS 23,8\"", "Définition": "1920 × 1080", "Fréquence": "180 Hz", "Réponse": "1 ms", "HDR": "Non", "Connectique": "HDMI + DP"}},
    {"name": "ProArt 27\" 4K USB-C", "brand": "ASUS", "category": "monitor", "price": 549.00, "old_price": None, "stock": 7, "rating": 4.8, "featured": False, "badge": None, "description": "Écran 4K calibré usine 100% sRGB pour la photo, la vidéo et le graphisme pro.", "specs": {"Dalle": "IPS 27\"", "Définition": "3840 × 2160", "Fréquence": "60 Hz", "Réponse": "5 ms", "HDR": "HDR400", "Connectique": "HDMI + DP + USB-C 90 W"}},

    # ═══ CLAVIERS ════════════════════════════════════════════════════
    {"name": "Keychron K8 Pro", "brand": "Keychron", "category": "keyboard", "price": 99.00, "old_price": None, "stock": 16, "rating": 4.8, "featured": True, "badge": None, "description": "Clavier mécanique TKL sans fil hot-swap, compatible QMK/VIA pour les passionnés.", "specs": {"Format": "TKL (87 touches)", "Switches": "Mécaniques hot-swap", "Connexion": "Bluetooth + USB-C", "Rétroéclairage": "RGB", "Étanchéité": "Non"}},
    {"name": "Apex Pro TKL Gen 3", "brand": "SteelSeries", "category": "keyboard", "price": 199.00, "old_price": None, "stock": 11, "rating": 4.7, "featured": False, "badge": None, "description": "Switches magnétiques à actuation réglable, l'arme ultime des joueurs compétitifs.", "specs": {"Format": "TKL", "Switches": "Magnétiques OmniPoint 3.0", "Connexion": "USB-C", "Rétroéclairage": "RGB par touche", "Étanchéité": "Non"}},
    {"name": "G915 TKL Lightspeed", "brand": "Logitech", "category": "keyboard", "price": 199.00, "old_price": None, "stock": 9, "rating": 4.7, "featured": False, "badge": None, "description": "Clavier low-profile sans fil Lightspeed, fin, premium et ultra-réactif.", "specs": {"Format": "TKL", "Switches": "GL low-profile", "Connexion": "Lightspeed + Bluetooth", "Rétroéclairage": "RGB par touche", "Étanchéité": "Non"}},
    {"name": "MX Keys S", "brand": "Logitech", "category": "keyboard", "price": 109.00, "old_price": None, "stock": 14, "rating": 4.7, "featured": False, "badge": None, "description": "Clavier bureautique premium à frappe silencieuse, idéal productivité multi-appareils.", "specs": {"Format": "Full-size", "Switches": "Ciseaux", "Connexion": "Bluetooth + Logi Bolt", "Rétroéclairage": "Blanc adaptatif", "Étanchéité": "Non"}},
    {"name": "Huntsman V3 Pro Mini", "brand": "Razer", "category": "keyboard", "price": 179.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "Clavier 60% à switches analogiques optiques, actuation réglable pour le gaming.", "specs": {"Format": "60%", "Switches": "Optiques analogiques", "Connexion": "USB-C", "Rétroéclairage": "RGB Chroma", "Étanchéité": "Non"}},
    {"name": "K65 Plus Wireless", "brand": "Corsair", "category": "keyboard", "price": 129.00, "old_price": None, "stock": 12, "rating": 4.6, "featured": False, "badge": None, "description": "Clavier 75% sans fil pré-lubrifié, frappe douce et silencieuse hors de la boîte.", "specs": {"Format": "75%", "Switches": "MLX Red pré-lubrifiés", "Connexion": "2,4 GHz + BT + USB-C", "Rétroéclairage": "RGB", "Étanchéité": "Non"}},
    {"name": "MK120 Combo clavier+souris", "brand": "Logitech", "category": "keyboard", "price": 19.00, "old_price": None, "stock": 30, "rating": 4.3, "featured": False, "badge": "Petit prix", "description": "Ensemble clavier + souris filaire fiable et abordable pour la bureautique.", "specs": {"Format": "Full-size", "Switches": "Membrane", "Connexion": "USB filaire", "Rétroéclairage": "Non", "Étanchéité": "Résistant aux éclaboussures"}},

    # ═══ SOURIS ══════════════════════════════════════════════════════
    {"name": "DeathAdder V3 Pro", "brand": "Razer", "category": "mouse", "price": 139.00, "old_price": None, "stock": 13, "rating": 4.8, "featured": False, "badge": None, "description": "L'ergonomie légendaire DeathAdder en version sans fil ultra-légère et précise.", "specs": {"Poids": "63 g", "Capteur": "Focus Pro 30K", "Boutons": "5", "Connexion": "HyperSpeed sans fil", "Rétroéclairage": "Non"}},
    {"name": "MX Master 3S", "brand": "Logitech", "category": "mouse", "price": 109.00, "old_price": None, "stock": 18, "rating": 4.8, "featured": False, "badge": None, "description": "La souris productivité ultime : molette MagSpeed, clics silencieux et multi-appareils.", "specs": {"Poids": "141 g", "Capteur": "Darkfield 8000 DPI", "Boutons": "7", "Connexion": "Bluetooth + Logi Bolt", "Rétroéclairage": "Non"}},
    {"name": "M650 L", "brand": "Logitech", "category": "mouse", "price": 39.00, "old_price": None, "stock": 26, "rating": 4.6, "featured": False, "badge": "Petit prix", "description": "Souris sans fil silencieuse et confortable pour le quotidien, grande taille.", "specs": {"Poids": "101 g", "Capteur": "Optique 2000 DPI", "Boutons": "5", "Connexion": "Bluetooth + Logi Bolt", "Rétroéclairage": "Non"}},

    # ═══ CASQUES AUDIO ═══════════════════════════════════════════════
    {"name": "Atlas Air", "brand": "Logitech", "category": "headset", "price": 179.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "Casque ouvert ultra-léger au confort suspendu, scène sonore large et aérée.", "specs": {"Transducteurs": "40 mm Pro-G", "Connexion": "Lightspeed + Bluetooth", "Surround": "Dolby Atmos", "Micro": "Détachable", "Poids": "283 g"}},
    {"name": "H390 USB", "brand": "Logitech", "category": "headset", "price": 39.00, "old_price": None, "stock": 24, "rating": 4.4, "featured": False, "badge": "Petit prix", "description": "Casque USB filaire confortable avec micro antibruit, idéal visio et bureautique.", "specs": {"Transducteurs": "40 mm", "Connexion": "USB-A", "Surround": "Stéréo", "Micro": "Antibruit rotatif", "Poids": "270 g"}},
]
