# -*- coding: utf-8 -*-
"""Extension massive du catalogue VOLT PC — toutes catégories.

Ajouté via SEED_PRODUCTS.extend(EXTRA_PRODUCTS) (cf. seed.py). Aucun doublon
avec l'existant (comparaison par nom dans add_products.py). Clés de compat
conservées : gpu→tdp_w/length_mm, mobo→socket/ram_type/form_factor,
ram→ram_type, case→max_gpu_mm, psu→watts, cooling→sockets[].
"""

EXTRA_PRODUCTS = [
    # ═══ CARTES GRAPHIQUES ═══════════════════════════════════════════
    {"name": "GeForce RTX 5060 8 Go", "brand": "MSI", "category": "gpu", "price": 329.00, "old_price": None, "stock": 16, "rating": 4.4, "featured": False, "badge": None, "description": "Le 1080p haute fréquence avec DLSS 4 multi-frame generation, sobre et abordable.", "specs": {"GPU": "Blackwell GB206", "Mémoire": "8 Go GDDR7", "Boost": "2497 MHz", "TDP": "145 W", "Longueur": "200 mm", "tdp_w": 145, "length_mm": 200}},
    {"name": "GeForce RTX 5060 Ti 16 Go", "brand": "Gigabyte", "category": "gpu", "price": 449.00, "old_price": None, "stock": 13, "rating": 4.6, "featured": False, "badge": None, "description": "16 Go de VRAM pour le 1440p tranquille, un excellent rapport perf/prix Blackwell.", "specs": {"GPU": "Blackwell GB206", "Mémoire": "16 Go GDDR7", "Boost": "2572 MHz", "TDP": "180 W", "Longueur": "240 mm", "tdp_w": 180, "length_mm": 240}},
    {"name": "GeForce RTX 4060 Ti 16 Go", "brand": "MSI", "category": "gpu", "price": 459.00, "old_price": None, "stock": 11, "rating": 4.4, "featured": False, "badge": None, "description": "La version 16 Go pour faire durer en 1440p texturé, idéale création légère.", "specs": {"GPU": "Ada AD106", "Mémoire": "16 Go GDDR6", "Boost": "2535 MHz", "TDP": "165 W", "Longueur": "245 mm", "tdp_w": 165, "length_mm": 245}},
    {"name": "GeForce RTX 4070 Super", "brand": "ASUS", "category": "gpu", "price": 609.00, "old_price": None, "stock": 9, "rating": 4.7, "featured": False, "badge": None, "description": "Le sweet spot 1440p : performances en hausse face à la 4070 pour le même prix.", "specs": {"GPU": "Ada AD104", "Mémoire": "12 Go GDDR6X", "Boost": "2475 MHz", "TDP": "220 W", "Longueur": "267 mm", "tdp_w": 220, "length_mm": 267}},
    {"name": "GeForce RTX 4070 Ti Super", "brand": "Gigabyte", "category": "gpu", "price": 819.00, "old_price": None, "stock": 7, "rating": 4.7, "featured": False, "badge": None, "description": "16 Go et un bus élargi : du 1440p sans compromis et du 4K très jouable.", "specs": {"GPU": "Ada AD103", "Mémoire": "16 Go GDDR6X", "Boost": "2610 MHz", "TDP": "285 W", "Longueur": "300 mm", "tdp_w": 285, "length_mm": 300}},
    {"name": "GeForce RTX 4080 Super", "brand": "MSI", "category": "gpu", "price": 1099.00, "old_price": None, "stock": 5, "rating": 4.8, "featured": False, "badge": None, "description": "Le 4K haut de gamme efficace, à deux doigts de la 4090 pour bien moins cher.", "specs": {"GPU": "Ada AD103", "Mémoire": "16 Go GDDR6X", "Boost": "2550 MHz", "TDP": "320 W", "Longueur": "310 mm", "tdp_w": 320, "length_mm": 310}},
    {"name": "Radeon RX 9070 XT 16 Go", "brand": "Sapphire", "category": "gpu", "price": 689.00, "old_price": None, "stock": 8, "rating": 4.7, "featured": True, "badge": None, "description": "Le fer de lance RDNA 4 : du 1440p/4K musclé avec un ray tracing enfin convaincant.", "specs": {"GPU": "RDNA 4 Navi 48", "Mémoire": "16 Go GDDR6", "Boost": "2970 MHz", "TDP": "304 W", "Longueur": "320 mm", "tdp_w": 304, "length_mm": 320}},
    {"name": "Radeon RX 9070 16 Go", "brand": "XFX", "category": "gpu", "price": 599.00, "old_price": None, "stock": 9, "rating": 4.6, "featured": False, "badge": None, "description": "16 Go de VRAM et une efficacité remarquable pour le 1440p haut de gamme.", "specs": {"GPU": "RDNA 4 Navi 48", "Mémoire": "16 Go GDDR6", "Boost": "2520 MHz", "TDP": "220 W", "Longueur": "290 mm", "tdp_w": 220, "length_mm": 290}},
    {"name": "Radeon RX 9060 XT 16 Go", "brand": "PowerColor", "category": "gpu", "price": 379.00, "old_price": None, "stock": 12, "rating": 4.5, "featured": False, "badge": None, "description": "16 Go en milieu de gamme : le 1080p/1440p durable et abordable signé RDNA 4.", "specs": {"GPU": "RDNA 4 Navi 44", "Mémoire": "16 Go GDDR6", "Boost": "3130 MHz", "TDP": "150 W", "Longueur": "250 mm", "tdp_w": 150, "length_mm": 250}},
    {"name": "Radeon RX 7600 8 Go", "brand": "Sapphire", "category": "gpu", "price": 269.00, "old_price": None, "stock": 15, "rating": 4.4, "featured": False, "badge": None, "description": "Du 1080p fluide à petit prix, sobre et silencieux.", "specs": {"GPU": "RDNA 3 Navi 33", "Mémoire": "8 Go GDDR6", "Boost": "2655 MHz", "TDP": "165 W", "Longueur": "204 mm", "tdp_w": 165, "length_mm": 204}},
    {"name": "Radeon RX 7600 XT 16 Go", "brand": "ASRock", "category": "gpu", "price": 329.00, "old_price": None, "stock": 12, "rating": 4.5, "featured": False, "badge": None, "description": "16 Go pour le 1080p très détaillé et un peu de 1440p, parfait pour durer.", "specs": {"GPU": "RDNA 3 Navi 33", "Mémoire": "16 Go GDDR6", "Boost": "2755 MHz", "TDP": "190 W", "Longueur": "270 mm", "tdp_w": 190, "length_mm": 270}},
    {"name": "Radeon RX 7700 XT 12 Go", "brand": "Sapphire", "category": "gpu", "price": 449.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "12 Go et de belles performances en 1440p, un excellent rapport qualité/prix.", "specs": {"GPU": "RDNA 3 Navi 32", "Mémoire": "12 Go GDDR6", "Boost": "2599 MHz", "TDP": "245 W", "Longueur": "267 mm", "tdp_w": 245, "length_mm": 267}},
    {"name": "Radeon RX 7800 XT 16 Go", "brand": "PowerColor", "category": "gpu", "price": 539.00, "old_price": None, "stock": 9, "rating": 4.7, "featured": False, "badge": None, "description": "La reine du 1440p côté AMD : 16 Go et une rasterisation très généreuse.", "specs": {"GPU": "RDNA 3 Navi 32", "Mémoire": "16 Go GDDR6", "Boost": "2430 MHz", "TDP": "263 W", "Longueur": "267 mm", "tdp_w": 263, "length_mm": 267}},
    {"name": "Radeon RX 7900 GRE 16 Go", "brand": "Sapphire", "category": "gpu", "price": 599.00, "old_price": None, "stock": 7, "rating": 4.6, "featured": False, "badge": None, "description": "Le bon plan 1440p/4K : presque une 7900 XT pour un tarif plus doux.", "specs": {"GPU": "RDNA 3 Navi 31", "Mémoire": "16 Go GDDR6", "Boost": "2245 MHz", "TDP": "260 W", "Longueur": "280 mm", "tdp_w": 260, "length_mm": 280}},
    {"name": "Radeon RX 7900 XT 20 Go", "brand": "XFX", "category": "gpu", "price": 749.00, "old_price": None, "stock": 6, "rating": 4.7, "featured": False, "badge": None, "description": "20 Go de VRAM pour le 4K et la création, une grosse carte très endurante.", "specs": {"GPU": "RDNA 3 Navi 31", "Mémoire": "20 Go GDDR6", "Boost": "2394 MHz", "TDP": "315 W", "Longueur": "287 mm", "tdp_w": 315, "length_mm": 287}},
    {"name": "Radeon RX 7900 XTX 24 Go", "brand": "Sapphire", "category": "gpu", "price": 969.00, "old_price": None, "stock": 5, "rating": 4.8, "featured": False, "badge": None, "description": "Le haut de gamme AMD : 24 Go pour le 4K et un excellent niveau en rasterisation.", "specs": {"GPU": "RDNA 3 Navi 31", "Mémoire": "24 Go GDDR6", "Boost": "2500 MHz", "TDP": "355 W", "Longueur": "287 mm", "tdp_w": 355, "length_mm": 287}},
    {"name": "Radeon RX 6650 XT 8 Go", "brand": "ASRock", "category": "gpu", "price": 239.00, "old_price": None, "stock": 13, "rating": 4.4, "featured": False, "badge": None, "description": "Du 1080p compétitif à prix mini, idéal e-sport.", "specs": {"GPU": "RDNA 2 Navi 23", "Mémoire": "8 Go GDDR6", "Boost": "2635 MHz", "TDP": "180 W", "Longueur": "220 mm", "tdp_w": 180, "length_mm": 220}},
    {"name": "Radeon RX 6700 XT 12 Go", "brand": "Sapphire", "category": "gpu", "price": 329.00, "old_price": None, "stock": 11, "rating": 4.6, "featured": False, "badge": None, "description": "12 Go pour un 1440p confortable, un classique au rapport qualité/prix imbattable.", "specs": {"GPU": "RDNA 2 Navi 22", "Mémoire": "12 Go GDDR6", "Boost": "2581 MHz", "TDP": "230 W", "Longueur": "267 mm", "tdp_w": 230, "length_mm": 267}},
    {"name": "Radeon RX 6750 XT 12 Go", "brand": "PowerColor", "category": "gpu", "price": 369.00, "old_price": None, "stock": 9, "rating": 4.5, "featured": False, "badge": None, "description": "Version boostée de la 6700 XT pour grappiller quelques fps en 1440p.", "specs": {"GPU": "RDNA 2 Navi 22", "Mémoire": "12 Go GDDR6", "Boost": "2600 MHz", "TDP": "250 W", "Longueur": "270 mm", "tdp_w": 250, "length_mm": 270}},
    {"name": "Radeon RX 6800 XT 16 Go", "brand": "Sapphire", "category": "gpu", "price": 489.00, "old_price": None, "stock": 7, "rating": 4.6, "featured": False, "badge": None, "description": "16 Go et de grosses performances 1440p/4K en rastérisation pour un tarif d'occasion.", "specs": {"GPU": "RDNA 2 Navi 21", "Mémoire": "16 Go GDDR6", "Boost": "2250 MHz", "TDP": "300 W", "Longueur": "267 mm", "tdp_w": 300, "length_mm": 267}},
    {"name": "Radeon RX 6950 XT 16 Go", "brand": "XFX", "category": "gpu", "price": 599.00, "old_price": None, "stock": 5, "rating": 4.6, "featured": False, "badge": None, "description": "Le sommet RDNA 2 : du 4K brut pour qui privilégie la puissance pure au ray tracing.", "specs": {"GPU": "RDNA 2 Navi 21", "Mémoire": "16 Go GDDR6", "Boost": "2310 MHz", "TDP": "335 W", "Longueur": "320 mm", "tdp_w": 335, "length_mm": 320}},
    {"name": "Arc B580 12 Go", "brand": "Intel", "category": "gpu", "price": 289.00, "old_price": None, "stock": 12, "rating": 4.5, "featured": False, "badge": None, "description": "La nouvelle génération Battlemage d'Intel : 12 Go et un excellent rapport perf/prix 1440p.", "specs": {"GPU": "Xe2 BMG-G21", "Mémoire": "12 Go GDDR6", "Boost": "2670 MHz", "TDP": "190 W", "Longueur": "272 mm", "tdp_w": 190, "length_mm": 272}},
    {"name": "Arc A750 8 Go", "brand": "Intel", "category": "gpu", "price": 219.00, "old_price": None, "stock": 11, "rating": 4.3, "featured": False, "badge": None, "description": "Une alternative musclée en 1080p/1440p avec un excellent encodeur AV1.", "specs": {"GPU": "Xe-HPG ACM-G10", "Mémoire": "8 Go GDDR6", "Boost": "2400 MHz", "TDP": "225 W", "Longueur": "270 mm", "tdp_w": 225, "length_mm": 270}},
    {"name": "Arc A770 16 Go", "brand": "Intel", "category": "gpu", "price": 299.00, "old_price": None, "stock": 9, "rating": 4.3, "featured": False, "badge": None, "description": "16 Go pour la création et le 1440p, le porte-étendard de la première gen Arc.", "specs": {"GPU": "Xe-HPG ACM-G10", "Mémoire": "16 Go GDDR6", "Boost": "2400 MHz", "TDP": "225 W", "Longueur": "280 mm", "tdp_w": 225, "length_mm": 280}},

    # ═══ MÉMOIRE RAM ═════════════════════════════════════════════════
    {"name": "Value 8 Go DDR4-2666", "brand": "Crucial", "category": "ram", "price": 22.00, "old_price": None, "stock": 40, "rating": 4.4, "featured": False, "badge": "Petit prix", "description": "Barrette 8 Go pour une mise à niveau ou une config bureautique économique.", "specs": {"Capacité": "8 Go (1x8)", "Type": "DDR4", "Fréquence": "2666 MT/s", "Latence": "CL19", "Profils": "—", "ram_type": "DDR4"}},
    {"name": "Vengeance LPX 32 Go DDR4-3200", "brand": "Corsair", "category": "ram", "price": 62.00, "old_price": None, "stock": 30, "rating": 4.7, "featured": False, "badge": None, "description": "32 Go DDR4 fiables, le confort pour le jeu et le multitâche sur AM4/LGA1700.", "specs": {"Capacité": "32 Go (2x16)", "Type": "DDR4", "Fréquence": "3200 MT/s", "Latence": "CL16", "Profils": "XMP 2.0", "ram_type": "DDR4"}},
    {"name": "Trident Z RGB 16 Go DDR4-3600", "brand": "G.Skill", "category": "ram", "price": 55.00, "old_price": None, "stock": 24, "rating": 4.7, "featured": False, "badge": None, "description": "16 Go DDR4 rapides et lumineux, le combo idéal pour un Ryzen 5000.", "specs": {"Capacité": "16 Go (2x8)", "Type": "DDR4", "Fréquence": "3600 MT/s", "Latence": "CL18", "Profils": "XMP 2.0", "ram_type": "DDR4"}},
    {"name": "Fury Beast 64 Go DDR4-3200", "brand": "Kingston", "category": "ram", "price": 119.00, "old_price": None, "stock": 16, "rating": 4.7, "featured": False, "badge": None, "description": "64 Go DDR4 pour la création lourde et la virtualisation sur plateforme AM4.", "specs": {"Capacité": "64 Go (2x32)", "Type": "DDR4", "Fréquence": "3200 MT/s", "Latence": "CL16", "Profils": "XMP 2.0", "ram_type": "DDR4"}},
    {"name": "Value 16 Go DDR5-4800", "brand": "Crucial", "category": "ram", "price": 46.00, "old_price": None, "stock": 30, "rating": 4.5, "featured": False, "badge": None, "description": "Le ticket d'entrée DDR5 à la norme JEDEC, parfait pour démarrer sur AM5/LGA1700.", "specs": {"Capacité": "16 Go (2x8)", "Type": "DDR5", "Fréquence": "4800 MT/s", "Latence": "CL40", "Profils": "—", "ram_type": "DDR5"}},
    {"name": "Flare X5 32 Go DDR5-6000 CL30", "brand": "G.Skill", "category": "ram", "price": 109.00, "old_price": None, "stock": 22, "rating": 4.8, "featured": False, "badge": None, "description": "Le kit DDR5 optimisé AMD EXPO par excellence : 6000 CL30, stable et performant.", "specs": {"Capacité": "32 Go (2x16)", "Type": "DDR5", "Fréquence": "6000 MT/s", "Latence": "CL30", "Profils": "EXPO", "ram_type": "DDR5"}},
    {"name": "T-Force Delta RGB 32 Go DDR5-6400", "brand": "Teamgroup", "category": "ram", "price": 119.00, "old_price": None, "stock": 18, "rating": 4.6, "featured": False, "badge": None, "description": "32 Go DDR5 rapides au look RGB diffusant, pour configs modernes Intel et AMD.", "specs": {"Capacité": "32 Go (2x16)", "Type": "DDR5", "Fréquence": "6400 MT/s", "Latence": "CL32", "Profils": "EXPO + XMP 3.0", "ram_type": "DDR5"}},
    {"name": "Fury Renegade 48 Go DDR5-7200", "brand": "Kingston", "category": "ram", "price": 239.00, "old_price": None, "stock": 12, "rating": 4.7, "featured": False, "badge": None, "description": "48 Go haute fréquence pour les configs Intel poussées et la création exigeante.", "specs": {"Capacité": "48 Go (2x24)", "Type": "DDR5", "Fréquence": "7200 MT/s", "Latence": "CL38", "Profils": "XMP 3.0", "ram_type": "DDR5"}},
    {"name": "Trident Z5 RGB 96 Go DDR5-6400", "brand": "G.Skill", "category": "ram", "price": 329.00, "old_price": None, "stock": 8, "rating": 4.8, "featured": False, "badge": None, "description": "96 Go pour les stations de travail : un montage RAM monstrueux pour la 3D et la vidéo.", "specs": {"Capacité": "96 Go (2x48)", "Type": "DDR5", "Fréquence": "6400 MT/s", "Latence": "CL32", "Profils": "EXPO + XMP 3.0", "ram_type": "DDR5"}},

    # ═══ STOCKAGE ════════════════════════════════════════════════════
    {"name": "A400 480 Go SATA", "brand": "Kingston", "category": "storage", "price": 30.00, "old_price": None, "stock": 45, "rating": 4.5, "featured": False, "badge": "Petit prix", "description": "SSD SATA d'entrée pour booster un vieux PC ou ajouter du stockage à moindre coût.", "specs": {"Capacité": "480 Go", "Interface": "SATA III", "Lecture": "500 Mo/s", "Écriture": "450 Mo/s", "Format": "2.5\""}},
    {"name": "BX500 1 To SATA", "brand": "Crucial", "category": "storage", "price": 55.00, "old_price": None, "stock": 35, "rating": 4.5, "featured": False, "badge": None, "description": "1 To en SATA 2.5\" pour stocker jeux et fichiers à petit prix.", "specs": {"Capacité": "1 To", "Interface": "SATA III", "Lecture": "540 Mo/s", "Écriture": "500 Mo/s", "Format": "2.5\""}},
    {"name": "870 EVO 1 To SATA", "brand": "Samsung", "category": "storage", "price": 79.00, "old_price": None, "stock": 28, "rating": 4.8, "featured": False, "badge": None, "description": "Le SSD SATA de référence : endurant, rapide et fiable, idéal disque secondaire.", "specs": {"Capacité": "1 To", "Interface": "SATA III", "Lecture": "560 Mo/s", "Écriture": "530 Mo/s", "Endurance": "600 TBW", "Format": "2.5\""}},
    {"name": "980 1 To PCIe 3.0", "brand": "Samsung", "category": "storage", "price": 69.00, "old_price": None, "stock": 26, "rating": 4.7, "featured": False, "badge": None, "description": "NVMe Gen3 sans DRAM, sobre et efficace comme disque système.", "specs": {"Capacité": "1 To", "Interface": "PCIe 3.0 x4", "Lecture": "3500 Mo/s", "Écriture": "3000 Mo/s", "Endurance": "600 TBW", "Format": "M.2 2280"}},
    {"name": "WD Blue SN580 1 To", "brand": "Western Digital", "category": "storage", "price": 69.00, "old_price": None, "stock": 24, "rating": 4.6, "featured": False, "badge": None, "description": "1 To Gen4 silencieux et endurant, parfait pour un premier montage.", "specs": {"Capacité": "1 To", "Interface": "PCIe 4.0 x4", "Lecture": "4150 Mo/s", "Écriture": "4150 Mo/s", "Endurance": "600 TBW", "Format": "M.2 2280"}},
    {"name": "WD_Black SN850X 1 To", "brand": "Western Digital", "category": "storage", "price": 109.00, "old_price": None, "stock": 18, "rating": 4.8, "featured": False, "badge": None, "description": "Le NVMe Gen4 gaming par excellence : débits au top et latences minimes.", "specs": {"Capacité": "1 To", "Interface": "PCIe 4.0 x4", "Lecture": "7300 Mo/s", "Écriture": "6300 Mo/s", "Endurance": "600 TBW", "Format": "M.2 2280"}},
    {"name": "990 Pro 2 To", "brand": "Samsung", "category": "storage", "price": 159.00, "old_price": None, "stock": 16, "rating": 4.9, "featured": False, "badge": None, "description": "La référence Gen4 : 2 To ultra-rapides et endurants pour gamers et créateurs.", "specs": {"Capacité": "2 To", "Interface": "PCIe 4.0 x4", "Lecture": "7450 Mo/s", "Écriture": "6900 Mo/s", "Endurance": "1200 TBW", "Format": "M.2 2280"}},
    {"name": "FireCuda 530R 2 To Gen4", "brand": "Seagate", "category": "storage", "price": 189.00, "old_price": None, "stock": 12, "rating": 4.7, "featured": False, "badge": None, "description": "2 To Gen4 endurants pensés pour le jeu et la création intensive.", "specs": {"Capacité": "2 To", "Interface": "PCIe 4.0 x4", "Lecture": "7300 Mo/s", "Écriture": "6900 Mo/s", "Endurance": "2550 TBW", "Format": "M.2 2280"}},
    {"name": "T500 2 To PCIe 4.0", "brand": "Crucial", "category": "storage", "price": 139.00, "old_price": None, "stock": 16, "rating": 4.7, "featured": False, "badge": None, "description": "Le Gen4 efficace et frais de Crucial, excellent rapport perf/prix en 2 To.", "specs": {"Capacité": "2 To", "Interface": "PCIe 4.0 x4", "Lecture": "7400 Mo/s", "Écriture": "7000 Mo/s", "Endurance": "1200 TBW", "Format": "M.2 2280"}},
    {"name": "BarraCuda 4 To 5400 tr/min", "brand": "Seagate", "category": "storage", "price": 89.00, "old_price": None, "stock": 22, "rating": 4.4, "featured": False, "badge": None, "description": "4 To pour archiver à très bas coût au To : sauvegardes, médias et photos.", "specs": {"Capacité": "4 To", "Interface": "SATA III", "Vitesse": "5400 tr/min", "Cache": "256 Mo", "Format": "3.5\""}},
    {"name": "WD Red Plus 4 To NAS", "brand": "Western Digital", "category": "storage", "price": 109.00, "old_price": None, "stock": 16, "rating": 4.7, "featured": False, "badge": None, "description": "Disque dur conçu pour fonctionner 24/7 en NAS, fiable et endurant.", "specs": {"Capacité": "4 To", "Interface": "SATA III", "Vitesse": "5400 tr/min", "Cache": "256 Mo", "Usage": "NAS / RAID", "Format": "3.5\""}},

    # ═══ CARTES MÈRES ════════════════════════════════════════════════
    {"name": "PRIME A520M-K", "brand": "ASUS", "category": "motherboard", "price": 59.00, "old_price": None, "stock": 20, "rating": 4.2, "featured": False, "badge": "Petit prix", "description": "La carte mère AM4 la plus économique pour un Ryzen 5500/5600 en DDR4.", "specs": {"Socket": "AM4", "Chipset": "A520", "Format": "Micro-ATX", "Mémoire": "2x DDR4 4600", "M.2": "1 slot Gen3", "Réseau": "1 GbE", "socket": "AM4", "ram_type": "DDR4", "form_factor": "mATX"}},
    {"name": "B450M DS3H V2", "brand": "Gigabyte", "category": "motherboard", "price": 75.00, "old_price": None, "stock": 18, "rating": 4.4, "featured": False, "badge": None, "description": "Le B450 increvable, compatible Ryzen 5000 après mise à jour BIOS.", "specs": {"Socket": "AM4", "Chipset": "B450", "Format": "Micro-ATX", "Mémoire": "4x DDR4 3600+", "M.2": "1 slot Gen3", "Réseau": "1 GbE", "socket": "AM4", "ram_type": "DDR4", "form_factor": "mATX"}},
    {"name": "B450 Tomahawk Max II", "brand": "MSI", "category": "motherboard", "price": 89.00, "old_price": None, "stock": 14, "rating": 4.6, "featured": False, "badge": None, "description": "La légende du rapport qualité/prix AM4 : VRM solides pour un 5800X3D.", "specs": {"Socket": "AM4", "Chipset": "B450", "Format": "ATX", "Mémoire": "4x DDR4 4133+", "M.2": "2 slots Gen3", "Réseau": "1 GbE", "socket": "AM4", "ram_type": "DDR4", "form_factor": "ATX"}},
    {"name": "B650M PG Riptide WiFi", "brand": "ASRock", "category": "motherboard", "price": 149.00, "old_price": None, "stock": 13, "rating": 4.5, "featured": False, "badge": None, "description": "B650 mATX abordable avec WiFi et PCIe 5.0, idéale config AM5 compacte.", "specs": {"Socket": "AM5", "Chipset": "B650", "Format": "Micro-ATX", "Mémoire": "4x DDR5 6400+", "M.2": "2 slots (1x Gen5)", "Réseau": "WiFi 6E + 2.5 GbE", "socket": "AM5", "ram_type": "DDR5", "form_factor": "mATX"}},
    {"name": "TUF Gaming B650-Plus WiFi", "brand": "ASUS", "category": "motherboard", "price": 189.00, "old_price": None, "stock": 11, "rating": 4.7, "featured": False, "badge": None, "description": "ATX robuste et endurante, la valeur sûre pour toute la gamme Ryzen AM5.", "specs": {"Socket": "AM5", "Chipset": "B650", "Format": "ATX", "Mémoire": "4x DDR5 7200+", "M.2": "2 slots (1x Gen5)", "Réseau": "WiFi 6 + 2.5 GbE", "socket": "AM5", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "X670 Aorus Elite AX", "brand": "Gigabyte", "category": "motherboard", "price": 259.00, "old_price": None, "stock": 8, "rating": 4.6, "featured": False, "badge": None, "description": "X670 complète pour overclocking RAM et stockage Gen5 sur AM5.", "specs": {"Socket": "AM5", "Chipset": "X670", "Format": "ATX", "Mémoire": "4x DDR5 8000+", "M.2": "4 slots (2x Gen5)", "Réseau": "WiFi 6E + 2.5 GbE", "socket": "AM5", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "B760M DS3H DDR4", "brand": "Gigabyte", "category": "motherboard", "price": 99.00, "old_price": None, "stock": 16, "rating": 4.4, "featured": False, "badge": None, "description": "B760 mATX en DDR4 pour une config Intel d'entrée économique.", "specs": {"Socket": "LGA1700", "Chipset": "B760", "Format": "Micro-ATX", "Mémoire": "4x DDR4 5333", "M.2": "2 slots Gen4", "Réseau": "1 GbE", "socket": "LGA1700", "ram_type": "DDR4", "form_factor": "mATX"}},
    {"name": "PRIME Z790-P WiFi DDR5", "brand": "ASUS", "category": "motherboard", "price": 199.00, "old_price": None, "stock": 10, "rating": 4.6, "featured": False, "badge": None, "description": "Z790 abordable avec WiFi pour overclocker un i7/i9 K en DDR5.", "specs": {"Socket": "LGA1700", "Chipset": "Z790", "Format": "ATX", "Mémoire": "4x DDR5 7600+", "M.2": "3 slots Gen4", "Réseau": "WiFi 6 + 2.5 GbE", "socket": "LGA1700", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "Z790 Aorus Elite AX DDR5", "brand": "Gigabyte", "category": "motherboard", "price": 269.00, "old_price": None, "stock": 8, "rating": 4.7, "featured": False, "badge": None, "description": "Haut de gamme LGA1700 : VRM costauds et connectique riche pour i9.", "specs": {"Socket": "LGA1700", "Chipset": "Z790", "Format": "ATX", "Mémoire": "4x DDR5 8266+", "M.2": "4 slots Gen4", "Réseau": "WiFi 6E + 2.5 GbE", "socket": "LGA1700", "ram_type": "DDR5", "form_factor": "ATX"}},
    {"name": "B860M-A WiFi DDR5", "brand": "ASRock", "category": "motherboard", "price": 169.00, "old_price": None, "stock": 10, "rating": 4.5, "featured": False, "badge": None, "description": "Nouvelle plateforme LGA1851 abordable pour les Core Ultra 200 en DDR5.", "specs": {"Socket": "LGA1851", "Chipset": "B860", "Format": "Micro-ATX", "Mémoire": "4x DDR5 7200+", "M.2": "2 slots (1x Gen5)", "Réseau": "WiFi 6E + 2.5 GbE", "socket": "LGA1851", "ram_type": "DDR5", "form_factor": "mATX"}},
    {"name": "Z890 Aorus Elite WiFi7", "brand": "Gigabyte", "category": "motherboard", "price": 289.00, "old_price": None, "stock": 8, "rating": 4.7, "featured": False, "badge": None, "description": "Z890 complète pour Core Ultra 200 : WiFi 7, Gen5 partout et VRM sérieux.", "specs": {"Socket": "LGA1851", "Chipset": "Z890", "Format": "ATX", "Mémoire": "4x DDR5 8600+", "M.2": "4 slots (2x Gen5)", "Réseau": "WiFi 7 + 2.5 GbE", "socket": "LGA1851", "ram_type": "DDR5", "form_factor": "ATX"}},

    # ═══ ALIMENTATIONS ═══════════════════════════════════════════════
    {"name": "System Power 10 550 W Bronze", "brand": "be quiet!", "category": "psu", "price": 59.00, "old_price": None, "stock": 24, "rating": 4.6, "featured": False, "badge": None, "description": "550 W 80+ Bronze silencieuse pour une config bureautique ou GPU d'entrée.", "specs": {"Puissance": "550 W", "Certification": "80+ Bronze", "Norme": "ATX 3.0", "Modulaire": "Non", "Garantie": "5 ans", "watts": 550}},
    {"name": "Pure Power 12 M 650 W Gold", "brand": "be quiet!", "category": "psu", "price": 89.00, "old_price": None, "stock": 20, "rating": 4.7, "featured": False, "badge": None, "description": "650 W 80+ Gold modulaire et silencieuse, câble 12V-2x6 inclus.", "specs": {"Puissance": "650 W", "Certification": "80+ Gold", "Norme": "ATX 3.0", "Modulaire": "Full", "Garantie": "10 ans", "watts": 650}},
    {"name": "RM750e ATX 3.0", "brand": "Corsair", "category": "psu", "price": 99.00, "old_price": None, "stock": 18, "rating": 4.7, "featured": False, "badge": None, "description": "750 W 80+ Gold full modulaire, idéale pour un GPU milieu/haut de gamme.", "specs": {"Puissance": "750 W", "Certification": "80+ Gold", "Norme": "ATX 3.0", "Modulaire": "Full", "Garantie": "7 ans", "watts": 750}},
    {"name": "RM850x ATX 3.1", "brand": "Corsair", "category": "psu", "price": 139.00, "old_price": None, "stock": 14, "rating": 4.8, "featured": False, "badge": None, "description": "850 W silencieuse et endurante, la valeur sûre pour une RTX 4080/4090.", "specs": {"Puissance": "850 W", "Certification": "80+ Gold", "Norme": "ATX 3.1", "Modulaire": "Full", "Garantie": "10 ans", "watts": 850}},
    {"name": "MPG A1000G PCIE5", "brand": "MSI", "category": "psu", "price": 159.00, "old_price": None, "stock": 11, "rating": 4.7, "featured": False, "badge": None, "description": "1000 W 80+ Gold avec connecteur 12VHPWR natif pour les GPU les plus gourmands.", "specs": {"Puissance": "1000 W", "Certification": "80+ Gold", "Norme": "ATX 3.0", "Modulaire": "Full", "Garantie": "10 ans", "watts": 1000}},
    {"name": "Vertex GX-1000 ATX 3.0", "brand": "Seasonic", "category": "psu", "price": 179.00, "old_price": None, "stock": 9, "rating": 4.8, "featured": False, "badge": None, "description": "1000 W premium signée Seasonic, ultra-stable et garantie 12 ans.", "specs": {"Puissance": "1000 W", "Certification": "80+ Gold", "Norme": "ATX 3.0", "Modulaire": "Full", "Garantie": "12 ans", "watts": 1000}},
    {"name": "V850 SFX Gold", "brand": "Cooler Master", "category": "psu", "price": 149.00, "old_price": None, "stock": 10, "rating": 4.7, "featured": False, "badge": None, "description": "850 W au format SFX compact pour les configs Mini-ITX puissantes.", "specs": {"Puissance": "850 W", "Certification": "80+ Gold", "Norme": "SFX", "Modulaire": "Full", "Garantie": "10 ans", "watts": 850}},
    {"name": "ROG Strix 1000W Gold Aura", "brand": "ASUS", "category": "psu", "price": 199.00, "old_price": None, "stock": 8, "rating": 4.8, "featured": False, "badge": None, "description": "1000 W haut de gamme avec ventilateur axial-tech et finitions soignées.", "specs": {"Puissance": "1000 W", "Certification": "80+ Gold", "Norme": "ATX 3.0", "Modulaire": "Full", "Garantie": "10 ans", "watts": 1000}},

    # ═══ BOÎTIERS ════════════════════════════════════════════════════
    {"name": "Versa H17 mATX", "brand": "Thermaltake", "category": "case", "price": 45.00, "old_price": None, "stock": 24, "rating": 4.2, "featured": False, "badge": "Petit prix", "description": "Boîtier mATX simple et abordable pour une première config propre.", "specs": {"Format": "Micro-ATX", "GPU max": "350 mm", "Ventilateurs": "Jusqu'à 4", "Façade": "Pleine", "Baies": "2x 2.5\" + 1x 3.5\"", "max_gpu_mm": 350}},
    {"name": "Pop Air RGB", "brand": "Fractal Design", "category": "case", "price": 79.00, "old_price": None, "stock": 18, "rating": 4.6, "featured": False, "badge": None, "description": "Bon flux d'air et style scandinave, livré avec 3 ventilateurs ARGB.", "specs": {"Format": "ATX", "GPU max": "405 mm", "Radiateurs": "2x 360 mm", "Façade": "Maille", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 405}},
    {"name": "Phanteks Eclipse G360A", "brand": "Phanteks", "category": "case", "price": 89.00, "old_price": None, "stock": 16, "rating": 4.6, "featured": False, "badge": None, "description": "Très bon flux d'air avec 3 ventilateurs ARGB inclus, montage facile.", "specs": {"Format": "ATX", "GPU max": "400 mm", "Radiateurs": "2x 360 mm", "Façade": "Maille", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 400}},
    {"name": "Lancool 216 RGB", "brand": "Lian Li", "category": "case", "price": 99.00, "old_price": None, "stock": 15, "rating": 4.7, "featured": False, "badge": None, "description": "Flux d'air exceptionnel grâce à ses gros ventilateurs 160 mm en façade.", "specs": {"Format": "ATX", "GPU max": "392 mm", "Radiateurs": "2x 360 mm", "Façade": "Maille", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 392}},
    {"name": "MasterBox NR200P", "brand": "Cooler Master", "category": "case", "price": 99.00, "old_price": None, "stock": 13, "rating": 4.7, "featured": False, "badge": None, "description": "Le boîtier Mini-ITX de référence : compact, bien pensé et compatible AIO.", "specs": {"Format": "Mini-ITX", "GPU max": "330 mm", "Radiateurs": "1x 280 mm", "Façade": "Pleine + verre", "Baies": "2x 2.5\" + 1x 3.5\"", "max_gpu_mm": 330}},
    {"name": "2500X mATX", "brand": "Corsair", "category": "case", "price": 129.00, "old_price": None, "stock": 12, "rating": 4.6, "featured": False, "badge": None, "description": "Mini-tour mATX double chambre, esthétique panoramique et excellent airflow.", "specs": {"Format": "Micro-ATX", "GPU max": "400 mm", "Radiateurs": "2x 360 mm", "Façade": "Verre + maille", "Baies": "2x 2.5\" + 1x 3.5\"", "max_gpu_mm": 400}},
    {"name": "Meshify 2 Compact", "brand": "Fractal Design", "category": "case", "price": 139.00, "old_price": None, "stock": 11, "rating": 4.8, "featured": False, "badge": None, "description": "Le grand classique du montage : silence, flux d'air et finitions au top.", "specs": {"Format": "ATX", "GPU max": "360 mm", "Radiateurs": "2x 360 mm", "Façade": "Maille", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 360}},
    {"name": "5000D Airflow", "brand": "Corsair", "category": "case", "price": 159.00, "old_price": None, "stock": 10, "rating": 4.8, "featured": False, "badge": None, "description": "Grand frère du 4000D : espace généreux et gestion des câbles exemplaire.", "specs": {"Format": "ATX / E-ATX", "GPU max": "420 mm", "Radiateurs": "2x 360 mm", "Façade": "Maille", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 420}},
    {"name": "O11 Vision Compact", "brand": "Lian Li", "category": "case", "price": 169.00, "old_price": None, "stock": 9, "rating": 4.8, "featured": False, "badge": None, "description": "Trois faces vitrées pour une vitrine de montage spectaculaire.", "specs": {"Format": "ATX / E-ATX", "GPU max": "455 mm", "Radiateurs": "3x 360 mm", "Façade": "Verre trempé", "Baies": "2x 2.5\" + 2x 3.5\"", "max_gpu_mm": 455}},

    # ═══ REFROIDISSEMENT ═════════════════════════════════════════════
    {"name": "SE-214-XT", "brand": "ID-Cooling", "category": "cooling", "price": 25.00, "old_price": None, "stock": 30, "rating": 4.4, "featured": False, "badge": "Petit prix", "description": "Ventirad ultra-abordable et efficace pour les CPU d'entrée et milieu de gamme.", "specs": {"Type": "Ventirad air", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "1x 120 mm PWM", "Hauteur": "150 mm", "TDP supporté": "130 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "Phantom Spirit 120 SE", "brand": "Thermalright", "category": "cooling", "price": 39.00, "old_price": None, "stock": 24, "rating": 4.8, "featured": False, "badge": None, "description": "Double tour ultra-performant qui humilie des ventirads bien plus chers.", "specs": {"Type": "Ventirad air", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "2x 120 mm PWM", "Hauteur": "157 mm", "TDP supporté": "245 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "AK500", "brand": "DeepCool", "category": "cooling", "price": 49.00, "old_price": None, "stock": 20, "rating": 4.6, "featured": False, "badge": None, "description": "Simple tour compact et performant, idéal pour les boîtiers serrés.", "specs": {"Type": "Ventirad air", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "1x 120 mm PWM", "Hauteur": "158 mm", "TDP supporté": "220 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "NH-U12S redux", "brand": "Noctua", "category": "cooling", "price": 55.00, "old_price": None, "stock": 16, "rating": 4.8, "featured": False, "badge": None, "description": "La fiabilité Noctua dans un format compact, silencieux et increvable.", "specs": {"Type": "Ventirad air", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "1x 120 mm PWM", "Hauteur": "158 mm", "TDP supporté": "180 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "Dark Rock Pro 5", "brand": "be quiet!", "category": "cooling", "price": 99.00, "old_price": None, "stock": 12, "rating": 4.8, "featured": False, "badge": None, "description": "Mastodonte du refroidissement à air, quasi inaudible même sous un i9.", "specs": {"Type": "Ventirad air", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "1x 135 mm + 1x 120 mm", "Hauteur": "168 mm", "TDP supporté": "270 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "LE520 240 AIO", "brand": "DeepCool", "category": "cooling", "price": 69.00, "old_price": None, "stock": 14, "rating": 4.5, "featured": False, "badge": None, "description": "AIO 240 mm abordable et fiable pour rafraîchir un CPU milieu de gamme.", "specs": {"Type": "AIO 240 mm", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "2x 120 mm PWM", "Pompe": "2400 tr/min", "TDP supporté": "260 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "Kraken 240 RGB", "brand": "NZXT", "category": "cooling", "price": 119.00, "old_price": None, "stock": 11, "rating": 4.6, "featured": False, "badge": None, "description": "AIO 240 mm avec écran d'infos et pompe silencieuse, finition premium.", "specs": {"Type": "AIO 240 mm", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "2x 120 mm PWM", "Pompe": "2800 tr/min", "TDP supporté": "280 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},
    {"name": "Galahad II Trinity 360", "brand": "Lian Li", "category": "cooling", "price": 129.00, "old_price": None, "stock": 10, "rating": 4.7, "featured": False, "badge": None, "description": "AIO 360 mm performant et élégant, parfait pour dompter un Ryzen 9 ou i9.", "specs": {"Type": "AIO 360 mm", "Sockets": "AM5 / AM4 / LGA1700", "Ventilateurs": "3x 120 mm PWM ARGB", "Pompe": "2900 tr/min", "TDP supporté": "350 W", "sockets": ["AM5", "AM4", "LGA1700", "LGA1851"]}},

    # ═══ ÉCRANS ══════════════════════════════════════════════════════
    {"name": "24MP400 24\" IPS 75 Hz", "brand": "LG", "category": "monitor", "price": 89.00, "old_price": None, "stock": 24, "rating": 4.4, "featured": False, "badge": "Petit prix", "description": "Écran bureautique IPS fin et élégant, idéal pour le travail et la navigation.", "specs": {"Dalle": "IPS 23,8\"", "Définition": "1920 × 1080", "Fréquence": "75 Hz", "Réponse": "5 ms", "HDR": "Non", "Connectique": "HDMI + VGA"}},
    {"name": "24E1N1300A 24\" 100 Hz", "brand": "Philips", "category": "monitor", "price": 99.00, "old_price": None, "stock": 20, "rating": 4.4, "featured": False, "badge": None, "description": "IPS 100 Hz abordable avec dalle plate et bords fins, polyvalent.", "specs": {"Dalle": "IPS 23,8\"", "Définition": "1920 × 1080", "Fréquence": "100 Hz", "Réponse": "4 ms", "HDR": "Non", "Connectique": "HDMI + VGA"}},
    {"name": "MOBIUZ EX2710S 27\" 165 Hz", "brand": "BenQ", "category": "monitor", "price": 199.00, "old_price": None, "stock": 14, "rating": 4.6, "featured": False, "badge": None, "description": "27\" IPS 165 Hz avec haut-parleurs traités, excellent pour le jeu et le film.", "specs": {"Dalle": "IPS 27\"", "Définition": "1920 × 1080", "Fréquence": "165 Hz", "Réponse": "1 ms", "HDR": "HDR10", "Connectique": "DP + 2x HDMI"}},
    {"name": "Odyssey G4 27\" 240 Hz IPS", "brand": "Samsung", "category": "monitor", "price": 249.00, "old_price": None, "stock": 12, "rating": 4.6, "featured": False, "badge": None, "description": "240 Hz en 1080p IPS pour la compétition pure et le jeu nerveux.", "specs": {"Dalle": "IPS 27\"", "Définition": "1920 × 1080", "Fréquence": "240 Hz", "Réponse": "1 ms", "HDR": "HDR10", "Connectique": "DP + HDMI"}},
    {"name": "M27Q 27\" 1440p 170 Hz KVM", "brand": "Gigabyte", "category": "monitor", "price": 269.00, "old_price": None, "stock": 12, "rating": 4.7, "featured": False, "badge": None, "description": "Le best-seller 1440p 170 Hz avec switch KVM intégré, polyvalent jeu/travail.", "specs": {"Dalle": "IPS 27\"", "Définition": "2560 × 1440", "Fréquence": "170 Hz", "Réponse": "1 ms", "HDR": "HDR400", "Connectique": "DP + 2x HDMI + USB-C"}},
    {"name": "Odyssey G5 32\" 1440p 165 Hz", "brand": "Samsung", "category": "monitor", "price": 279.00, "old_price": None, "stock": 11, "rating": 4.5, "featured": False, "badge": None, "description": "Grand 32\" incurvé 1440p 165 Hz pour une immersion gaming généreuse.", "specs": {"Dalle": "VA 32\" incurvée", "Définition": "2560 × 1440", "Fréquence": "165 Hz", "Réponse": "1 ms", "HDR": "HDR10", "Connectique": "DP + HDMI"}},
    {"name": "27GP850-B 27\" 1440p 180 Hz", "brand": "LG", "category": "monitor", "price": 299.00, "old_price": None, "stock": 10, "rating": 4.7, "featured": False, "badge": None, "description": "Dalle Nano IPS 1440p ultra-réactive jusqu'à 180 Hz, couleurs superbes.", "specs": {"Dalle": "Nano IPS 27\"", "Définition": "2560 × 1440", "Fréquence": "180 Hz", "Réponse": "1 ms", "HDR": "HDR400", "Connectique": "DP + 2x HDMI"}},
    {"name": "CU34G2X 34\" UWQHD 144 Hz", "brand": "AOC", "category": "monitor", "price": 329.00, "old_price": None, "stock": 9, "rating": 4.6, "featured": False, "badge": None, "description": "Ultrawide 34\" incurvé 144 Hz pour une immersion totale en jeu et productivité.", "specs": {"Dalle": "VA 34\" incurvée", "Définition": "3440 × 1440", "Fréquence": "144 Hz", "Réponse": "1 ms", "HDR": "HDR400", "Connectique": "DP + 2x HDMI"}},
    {"name": "U2723QE 27\" 4K USB-C", "brand": "Dell", "category": "monitor", "price": 499.00, "old_price": None, "stock": 8, "rating": 4.8, "featured": False, "badge": None, "description": "27\" 4K IPS Black pour les créateurs : colorimétrie exemplaire et hub USB-C.", "specs": {"Dalle": "IPS Black 27\"", "Définition": "3840 × 2160", "Fréquence": "60 Hz", "Réponse": "5 ms", "HDR": "HDR400", "Connectique": "USB-C 90W + DP + 2x HDMI"}},
    {"name": "M32U 32\" 4K 144 Hz", "brand": "Gigabyte", "category": "monitor", "price": 599.00, "old_price": None, "stock": 7, "rating": 4.7, "featured": False, "badge": None, "description": "32\" 4K 144 Hz avec KVM : le compromis idéal jeu en 4K et grande surface de travail.", "specs": {"Dalle": "IPS 32\"", "Définition": "3840 × 2160", "Fréquence": "144 Hz", "Réponse": "1 ms", "HDR": "HDR400", "Connectique": "DP + 2x HDMI 2.1 + USB-C"}},
    {"name": "MAG 321UPX QD-OLED 4K", "brand": "MSI", "category": "monitor", "price": 899.00, "old_price": None, "stock": 5, "rating": 4.8, "featured": False, "badge": None, "description": "32\" QD-OLED 4K 240 Hz : noirs parfaits et fluidité extrême pour le jeu d'élite.", "specs": {"Dalle": "QD-OLED 31,5\"", "Définition": "3840 × 2160", "Fréquence": "240 Hz", "Réponse": "0,03 ms", "HDR": "DisplayHDR True Black 400", "Connectique": "DP 2.1 + 2x HDMI 2.1 + USB-C"}},

    # ═══ CLAVIERS ════════════════════════════════════════════════════
    {"name": "K55 RGB Pro", "brand": "Corsair", "category": "keyboard", "price": 49.00, "old_price": None, "stock": 24, "rating": 4.4, "featured": False, "badge": None, "description": "Clavier membrane gaming silencieux avec RGB dynamique et touches macro.", "specs": {"Format": "Full-size", "Switches": "Membrane", "Connexion": "USB filaire", "Rétroéclairage": "RGB par zones", "Étanchéité": "IP42"}},
    {"name": "Apex 3 TKL", "brand": "SteelSeries", "category": "keyboard", "price": 49.00, "old_price": None, "stock": 20, "rating": 4.4, "featured": False, "badge": None, "description": "Membrane silencieuse résistante à l'eau au format TKL gain de place.", "specs": {"Format": "TKL", "Switches": "Membrane silencieuse", "Connexion": "USB filaire", "Rétroéclairage": "RGB 8 zones", "Étanchéité": "IP32"}},
    {"name": "G413 SE TKL", "brand": "Logitech", "category": "keyboard", "price": 59.00, "old_price": None, "stock": 18, "rating": 4.5, "featured": False, "badge": None, "description": "Clavier mécanique sobre à châssis aluminium, fiable et sans fioritures.", "specs": {"Format": "TKL", "Switches": "Tactiles mécaniques", "Connexion": "USB filaire", "Rétroéclairage": "Blanc", "Châssis": "Aluminium"}},
    {"name": "RK84 sans-fil", "brand": "Royal Kludge", "category": "keyboard", "price": 69.00, "old_price": None, "stock": 16, "rating": 4.5, "featured": False, "badge": None, "description": "Clavier mécanique 75 % hot-swap triple mode, excellent rapport qualité/prix.", "specs": {"Format": "75 %", "Switches": "Hot-swap mécaniques", "Connexion": "Bluetooth + 2,4 GHz + USB-C", "Rétroéclairage": "RGB", "Hot-swap": "Oui"}},
    {"name": "V6 QMK", "brand": "Keychron", "category": "keyboard", "price": 79.00, "old_price": None, "stock": 15, "rating": 4.7, "featured": False, "badge": None, "description": "Full-size personnalisable QMK/VIA, hot-swap et construction massive.", "specs": {"Format": "Full-size", "Switches": "Gateron hot-swap", "Connexion": "USB-C filaire", "Rétroéclairage": "RGB", "Hot-swap": "Oui"}},
    {"name": "Air75 V2", "brand": "NuPhy", "category": "keyboard", "price": 109.00, "old_price": None, "stock": 13, "rating": 4.7, "featured": False, "badge": None, "description": "Clavier mécanique fin et sans-fil au design soigné, frappe agréable low-profile.", "specs": {"Format": "75 %", "Switches": "Gateron low-profile", "Connexion": "Bluetooth + 2,4 GHz + USB-C", "Rétroéclairage": "RGB", "Profil": "Low-profile"}},
    {"name": "BlackWidow V4 X", "brand": "Razer", "category": "keyboard", "price": 149.00, "old_price": None, "stock": 12, "rating": 4.6, "featured": False, "badge": None, "description": "Mécanique gaming avec switches Razer Green cliquetants et repose-poignet.", "specs": {"Format": "Full-size", "Switches": "Razer Green mécaniques", "Connexion": "USB filaire", "Rétroéclairage": "RGB Chroma", "Macros": "Dédiées"}},
    {"name": "K70 RGB Pro", "brand": "Corsair", "category": "keyboard", "price": 159.00, "old_price": None, "stock": 11, "rating": 4.7, "featured": False, "badge": None, "description": "Le mécanique gaming de référence : châssis alu, switches Cherry MX et polling 8000 Hz.", "specs": {"Format": "Full-size", "Switches": "Cherry MX Red", "Connexion": "USB filaire", "Rétroéclairage": "RGB par touche", "Polling": "8000 Hz"}},

    # ═══ SOURIS ══════════════════════════════════════════════════════
    {"name": "Rival 3", "brand": "SteelSeries", "category": "mouse", "price": 35.00, "old_price": None, "stock": 30, "rating": 4.5, "featured": False, "badge": "Petit prix", "description": "Souris gaming filaire légère et fiable, capteur précis pour pas cher.", "specs": {"Poids": "77 g", "Capteur": "TrueMove Core 8500 DPI", "Boutons": "6", "Connexion": "USB filaire", "Rétroéclairage": "RGB 3 zones"}},
    {"name": "G502 HERO", "brand": "Logitech", "category": "mouse", "price": 49.00, "old_price": None, "stock": 26, "rating": 4.8, "featured": False, "badge": None, "description": "La souris la plus vendue au monde : 11 boutons et poids ajustable, filaire.", "specs": {"Poids": "121 g", "Capteur": "Hero 25 600 DPI", "Boutons": "11", "Connexion": "USB filaire", "Poids ajustable": "Oui"}},
    {"name": "Basilisk V3", "brand": "Razer", "category": "mouse", "price": 59.00, "old_price": None, "stock": 22, "rating": 4.7, "featured": False, "badge": None, "description": "Ergonomique avec molette inclinable HyperScroll et 11 commandes programmables.", "specs": {"Poids": "101 g", "Capteur": "Focus+ 26 000 DPI", "Boutons": "11", "Connexion": "USB filaire", "Rétroéclairage": "RGB Chroma"}},
    {"name": "DeathAdder V3", "brand": "Razer", "category": "mouse", "price": 69.00, "old_price": None, "stock": 18, "rating": 4.7, "featured": False, "badge": None, "description": "La forme ergonomique iconique en version ultra-légère filaire (59 g).", "specs": {"Poids": "59 g", "Capteur": "Focus Pro 30 000 DPI", "Boutons": "5", "Connexion": "USB filaire", "Polling": "1000 Hz"}},
    {"name": "G502 X PLUS", "brand": "Logitech", "category": "mouse", "price": 79.00, "old_price": None, "stock": 16, "rating": 4.7, "featured": False, "badge": None, "description": "La G502 réinventée : sans-fil Lightspeed, switches optiques et RGB LIGHTSYNC.", "specs": {"Poids": "106 g", "Capteur": "Hero 2 25 600 DPI", "Boutons": "13", "Connexion": "Lightspeed 2,4 GHz", "Autonomie": "120 h"}},
    {"name": "X2V2 sans fil", "brand": "Pulsar", "category": "mouse", "price": 89.00, "old_price": None, "stock": 13, "rating": 4.7, "featured": False, "badge": None, "description": "Souris e-sport symétrique ultra-légère plébiscitée par les joueurs exigeants.", "specs": {"Poids": "52 g", "Capteur": "XS-1 26 000 DPI", "Boutons": "5", "Connexion": "2,4 GHz", "Polling": "1000 Hz"}},
    {"name": "Viper V2 Pro", "brand": "Razer", "category": "mouse", "price": 99.00, "old_price": None, "stock": 12, "rating": 4.8, "featured": False, "badge": None, "description": "Symétrique ultra-légère (58 g) sans-fil, une référence absolue en compétition.", "specs": {"Poids": "58 g", "Capteur": "Focus Pro 30 000 DPI", "Boutons": "5", "Connexion": "HyperSpeed 2,4 GHz", "Autonomie": "80 h"}},
    {"name": "Naga V2 Pro", "brand": "Razer", "category": "mouse", "price": 149.00, "old_price": None, "stock": 9, "rating": 4.7, "featured": False, "badge": None, "description": "La souris MMO/MOBA ultime : flancs interchangeables jusqu'à 19 boutons.", "specs": {"Poids": "112 g", "Capteur": "Focus Pro 30 000 DPI", "Boutons": "Jusqu'à 19", "Connexion": "HyperSpeed 2,4 GHz", "Autonomie": "150 h"}},

    # ═══ CASQUES ═════════════════════════════════════════════════════
    {"name": "Cloud Alpha", "brand": "HyperX", "category": "headset", "price": 89.00, "old_price": None, "stock": 24, "rating": 4.7, "featured": False, "badge": None, "description": "Casque filaire au son équilibré et au confort légendaire, valeur sûre.", "specs": {"Transducteurs": "50 mm double chambre", "Connexion": "Jack 3,5 mm", "Surround": "Stéréo", "Micro": "Détachable", "Poids": "298 g"}},
    {"name": "BlackShark V2", "brand": "Razer", "category": "headset", "price": 89.00, "old_price": None, "stock": 20, "rating": 4.7, "featured": False, "badge": None, "description": "Léger et précis avec un excellent micro, plébiscité par les compétiteurs.", "specs": {"Transducteurs": "50 mm TriForce", "Connexion": "Jack 3,5 mm + USB DAC", "Surround": "THX Spatial", "Micro": "Détachable cardioïde", "Poids": "262 g"}},
    {"name": "Stealth 600 Gen 3", "brand": "Turtle Beach", "category": "headset", "price": 99.00, "old_price": None, "stock": 18, "rating": 4.5, "featured": False, "badge": None, "description": "Sans-fil abordable multiplateforme avec grande autonomie et bonne isolation.", "specs": {"Transducteurs": "50 mm", "Connexion": "2,4 GHz + Bluetooth", "Surround": "Spatial", "Micro": "Escamotable", "Autonomie": "80 h"}},
    {"name": "HS80 RGB Wireless", "brand": "Corsair", "category": "headset", "price": 129.00, "old_price": None, "stock": 15, "rating": 4.6, "featured": False, "badge": None, "description": "Sans-fil haut de gamme au son Dolby Atmos et micro broadcast de qualité.", "specs": {"Transducteurs": "50 mm néodyme", "Connexion": "2,4 GHz Slipstream", "Surround": "Dolby Atmos", "Micro": "Omnidirectionnel", "Autonomie": "20 h"}},
    {"name": "Arctis Nova 7", "brand": "SteelSeries", "category": "headset", "price": 149.00, "old_price": None, "stock": 13, "rating": 4.7, "featured": False, "badge": None, "description": "Sans-fil polyvalent avec double connexion 2,4 GHz + Bluetooth simultanés.", "specs": {"Transducteurs": "40 mm néodyme", "Connexion": "2,4 GHz + Bluetooth", "Surround": "360 Spatial Audio", "Micro": "Rétractable ClearCast", "Autonomie": "38 h"}},
    {"name": "BlackShark V2 Pro", "brand": "Razer", "category": "headset", "price": 179.00, "old_price": None, "stock": 11, "rating": 4.7, "featured": False, "badge": None, "description": "La version sans-fil du BlackShark V2 : ultra-léger, autonome et précis en compétition.", "specs": {"Transducteurs": "50 mm TriForce Titanium", "Connexion": "HyperSpeed 2,4 GHz", "Surround": "THX Spatial", "Micro": "Détachable HyperClear", "Autonomie": "70 h"}},
    {"name": "HD 560S", "brand": "Sennheiser", "category": "headset", "price": 169.00, "old_price": None, "stock": 10, "rating": 4.8, "featured": False, "badge": None, "description": "Casque audiophile ouvert à la scène sonore large, sublime pour le jeu immersif et la musique.", "specs": {"Transducteurs": "38 mm dynamiques", "Connexion": "Jack 6,35 mm", "Type": "Ouvert", "Micro": "Non (à ajouter)", "Impédance": "120 ohms"}},
    {"name": "Virtuoso Pro", "brand": "Corsair", "category": "headset", "price": 199.00, "old_price": None, "stock": 9, "rating": 4.7, "featured": False, "badge": None, "description": "Casque ouvert haut de gamme avec micro broadcast détachable de qualité studio.", "specs": {"Transducteurs": "50 mm graphène", "Connexion": "Jack 3,5 mm + USB", "Type": "Ouvert", "Micro": "Détachable broadcast", "Impédance": "32 ohms"}},
]
